using System;
using Microsoft.EntityFrameworkCore.Migrations;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using Pgvector;

#nullable disable

namespace VibeApp.Data.Migrations
{
    /// <inheritdoc />
    public partial class AddUserProfileEmbedding : Migration
    {
        /// <inheritdoc />
        protected override void Up(MigrationBuilder migrationBuilder)
        {
            // Check if table already exists before creating it
            migrationBuilder.Sql(@"
                DO $$ 
                BEGIN
                    IF NOT EXISTS (SELECT FROM pg_tables WHERE schemaname = 'public' AND tablename = 'UserProfileEmbeddings') THEN
                        CREATE TABLE ""UserProfileEmbeddings"" (
                            ""Id"" integer GENERATED BY DEFAULT AS IDENTITY,
                            ""UserProfileId"" integer NOT NULL,
                            ""Embedding"" vector(1536) NOT NULL,
                            ""CreatedAt"" timestamp with time zone NOT NULL,
                            ""UpdatedAt"" timestamp with time zone,
                            CONSTRAINT ""PK_UserProfileEmbeddings"" PRIMARY KEY (""Id""),
                            CONSTRAINT ""FK_UserProfileEmbeddings_UserProfiles_UserProfileId"" FOREIGN KEY (""UserProfileId"") REFERENCES ""UserProfiles"" (""Id"") ON DELETE CASCADE
                        );
                        
                        CREATE UNIQUE INDEX ""IX_UserProfileEmbeddings_UserProfileId"" ON ""UserProfileEmbeddings"" (""UserProfileId"");
                    END IF;
                END $$;
            ");
        }

        /// <inheritdoc />
        protected override void Down(MigrationBuilder migrationBuilder)
        {
            migrationBuilder.Sql(@"
                DO $$ 
                BEGIN
                    IF EXISTS (SELECT FROM pg_tables WHERE schemaname = 'public' AND tablename = 'UserProfileEmbeddings') THEN
                        DROP TABLE ""UserProfileEmbeddings"";
                    END IF;
                END $$;
            ");
        }
    }
}
