namespace VibeApp.Core.DTOs;

/// <summary>
/// Response DTO for RAG search
/// </summary>
public class RagSearchResponseDto
{
    /// <summary>
    /// Original query
    /// </summary>
    public string Query { get; set; } = string.Empty;

    /// <summary>
    /// Natural language response generated by LLM (if GenerateResponse was true)
    /// </summary>
    public string? Answer { get; set; }

    /// <summary>
    /// List of matching user profiles with similarity scores
    /// </summary>
    public List<ProfileSearchResultDto> Results { get; set; } = new();

    /// <summary>
    /// Total number of results found
    /// </summary>
    public int TotalResults { get; set; }
}

/// <summary>
/// Individual profile search result
/// </summary>
public class ProfileSearchResultDto
{
    /// <summary>
    /// User profile ID
    /// </summary>
    public int Id { get; set; }

    /// <summary>
    /// User's name
    /// </summary>
    public string Name { get; set; } = string.Empty;

    /// <summary>
    /// User's bio/description
    /// </summary>
    public string Bio { get; set; } = string.Empty;

    /// <summary>
    /// User's skills
    /// </summary>
    public List<string> Skills { get; set; } = new();

    /// <summary>
    /// What user is looking for
    /// </summary>
    public List<string> LookingFor { get; set; } = new();

    /// <summary>
    /// Telegram handle
    /// </summary>
    public string Telegram { get; set; } = string.Empty;

    /// <summary>
    /// LinkedIn profile URL
    /// </summary>
    public string LinkedIn { get; set; } = string.Empty;

    /// <summary>
    /// Email address
    /// </summary>
    public string Email { get; set; } = string.Empty;

    /// <summary>
    /// City
    /// </summary>
    public string City { get; set; } = string.Empty;

    /// <summary>
    /// Country
    /// </summary>
    public string Country { get; set; } = string.Empty;

    /// <summary>
    /// Whether user has a startup
    /// </summary>
    public bool HasStartup { get; set; }

    /// <summary>
    /// Startup name (if has startup)
    /// </summary>
    public string? StartupName { get; set; }

    /// <summary>
    /// Startup stage (if has startup)
    /// </summary>
    public string? StartupStage { get; set; }

    /// <summary>
    /// What user can help with
    /// </summary>
    public string? CanHelp { get; set; }

    /// <summary>
    /// What user needs help with
    /// </summary>
    public string? NeedsHelp { get; set; }

    /// <summary>
    /// Cosine similarity score (0-1, higher is more similar)
    /// </summary>
    public float SimilarityScore { get; set; }
}

